linters:
  disable-all: true
  enable:
    - bodyclose
    - canonicalheader
    - cyclop
    - depguard
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - gocognit
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - intrange
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilerr
    - nilnesserr
    - nilnil
    - nolintlint
    - perfsprint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - staticcheck
    - tagalign
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace

linters-settings:
  cyclop:
    max-complexity: 20

  depguard:
    rules:
      main:
        deny:
          - pkg: io/ioutil
            desc: use io instead

          - pkg: "math/rand$"
            desc: use math/rand/v2 instead

  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    check:
      - switch
      - map
    default-signifies-exhaustive: true

  staticcheck:
    checks:
      - all

  gosimple:
    checks:
      - all

  govet:
    enable-all: true

  gofumpt:
    extra-rules: true

  nakedret:
    max-func-lines: 0 # Disallow any naked returns

  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true

  usetesting:
    context-background: true
    context-todo: true
    os-chdir: true
    os-mkdir-temp: true
    os-setenv: true
    os-create-temp: true
    os-temp-dir: true

  revive:
    max-open-files: 256
    ignore-generated-header: true
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true # goconst does this

      - name: argument-limit
        arguments:
          - 5

      - name: cognitive-complexity
        disabled: true # gocognit does this

      - name: cyclomatic
        disabled: true # cyclop does this

      - name: exported
        arguments:
          - checkPrivateReceivers
          - checkPublicInterface

      - name: function-length
        disabled: true

      - name: function-result-limit
        arguments:
          - 3

      - name: import-shadowing
        disabled: true

      - name: line-length-limit
        disabled: true

      - name: redefines-builtin-id
        disabled: true # predeclared does this

      - name: unhandled-error
        arguments:
          # Apparently regexes for this don't work?
          - fmt\.Fprintln
          - fmt\.Fprintf
          - fmt\.Fprint
          - fmt\.Println
          - fmt\.Printf
          - fmt\.Print
          - strings\.Builder\.WriteString
