[tools]
golangci-lint = "latest"
typos = "latest"
vhs = "latest"
"aqua:charmbracelet/freeze" = "latest"
fd = "latest"
"go:go.uber.org/nilaway/cmd/nilaway" = "latest"
"go:golang.org/x/pkgsite/cmd/pkgsite" = "latest"

[vars]
COV_DATA = "coverage.out"

[tasks.tidy]
description = "Tidy dependencies in go.mod and go.sum"
run = "go mod tidy"
sources = ["**/*.go", "go.mod", "go.sum"]

[tasks.fmt]
description = "Run go fmt on all source files"
run = "golangci-lint fmt ./..."
sources = ["**/*.go", ".golangci.yml", "**/*.md"]

[tasks.test]
description = "Run the test suite"
usage = '''
arg "[args]..." help="Extra args to pass to go test"
'''
# -race needs CGO (https://go.dev/doc/articles/race_detector#Requirements)
env = { CGO_ENABLED = "1" }
run = "go test -race ./... {{arg(name='args', default='')}}"
sources = ["**/*.go", "**/testdata/**/*", "go.mod", "go.sum"]

[tasks.bench]
description = "Run all project benchmarks"
usage = '''
arg "[args]..." help="Extra args to pass to go test"
'''
run = "go test ./... -run None -benchmem -bench . {{arg(name='args', default='')}}"
sources = ["**/*.go"]

[tasks.lint]
description = "Run the linters and auto-fix if possible"
depends = ["fmt"]
run = ["golangci-lint run --fix", "typos", "nilaway ./..."]
sources = ["**/*.go", ".golangci.yml"]

[tasks.docs]
description = "Render the pkg docs locally"
raw = true
run = "pkgsite -open"

[tasks.demo]
description = "Render the demo gifs in parallel"
run = [
  'for file in ./docs/src/*.tape; do vhs "$file" & done; wait',
  "freeze ./examples/cover/main.go --config ./docs/src/freeze.json --output ./docs/img/demo.png --show-line-numbers",
]
sources = ["./docs/src/*.tape", "**/*.go"]
outputs = ["./docs/img/*.gif", "./docs/img/demo.png"]

[tasks.cov]
description = "Calculate test coverage (pass --open to view as HTML in a browser)"
usage = '''
flag "--open" help="Open the coverage report in a browser"
'''
run = '''
go test -race -cover -covermode atomic -coverprofile {{vars.COV_DATA}} ./...
if [ "${usage_open:-false}" = "true" ]; then
    go tool cover -html {{vars.COV_DATA}}
fi
'''
sources = ["**/*.go", "**/testdata/**/*", "go.mod", "go.sum"]
outputs = ["{{vars.COV_DATA}}"]

[tasks.check]
description = "Run tests and linting in one"
depends = ["test", "lint"]

[tasks.sloc]
description = "Print lines of code"
run = "fd . -e go | xargs wc -l | sort -nr | head"

[tasks.clean]
description = "Remove build artifacts and other clutter"
run = ["go clean ./...", "rm -rf *.out"]

[tasks.update]
description = "Updates dependencies in go.mod and go.sum"
run = ["go get -u ./...", "go mod tidy"]
